---
version: '3.9'

services:
  # You can comment this webserver section if you want to use another webserver/proxy
  web:
    container_name: motibus_web
    hostname: motibus_web
    #image: chocobozzz/peertube-webserver:latest
    # If you don't want to use the official image and build one from sources:
    build:
      context: ./images/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
     - '80'
    networks:
     - motibus-link
     - planet-link
    volumes:
      - type: bind
        # Switch sources if you downloaded the whole repository
        #source: ../../nginx/peertube
        source: ./images/nginx/peertube.conf
        target: /etc/nginx/conf.d/peertube.template
      - assets:/var/www/peertube/peertube-latest/client/dist:ro
      - ./var/peertube/data:/var/www/peertube/storage
    depends_on:
      - peertube
    restart: "always"

  peertube:
    container_name: motibus_peertube
    hostname: motibus_peertube
    image: motibus_peertube
    build:
      context: ./images/peertube
    networks:
      motibus-link:
        ipv4_address: 172.54.0.42
    env_file:
      - .env
    expose:
      - '9000'
    ports:
      - '1935:1935'
    volumes:
      - assets:/app/client/dist
      - ./var/peertube/data:/data
      - ./var/peertube/config:/config
    depends_on:
      - postgres
      - redis
      - postfix
    restart: "always"

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./var/db:/var/lib/postgresql/data
    restart: "always"
    networks:
     - motibus-link

  redis:
    image: redis:6-alpine
    volumes:
      - ./var/redis:/data
    restart: "always"
    networks:
     - motibus-link

  postfix:
    image: mwader/postfix-relay
    env_file:
      - .env
    volumes:
      - ./var/opendkim/keys:/etc/opendkim/keys
    restart: "always"
    networks:
     - motibus-link

networks:
  motibus-link:
    external: false
    ipam:
      driver: default
      config:
      - subnet:  172.54.0.0/16
  planet-link:
    external:
      name: planet-link

volumes:
  assets:
